version: "3.8"

services:
  api:
    networks:
      - otpforge-network
    build:
      target: development
    volumes:
      - ./:/usr/src/app
    environment:
      - NODE_ENV=development
    command: npm run dev

networks:
  otpforge-network:
    name: otpforge-network
    driver: bridge
