version: "3.8"

services:
  api:
    container_name: otpforge-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - PORT=${PORT}
      - REDIS_HOST=${REDIS_HOST}
      - OTP_LENGTH=${OTP_LENGTH}
      - INCLUDE_ALPHABETS=${INCLUDE_ALPHABETS}
      - INCLUDE_NUMBERS=${INCLUDE_NUMBERS}
      - OTP_VALIDITY=${OTP_VALIDITY}
      - MAX_ATTEMPTS=${MAX_ATTEMPTS}
      - COMPANY_NAME=${COMPANY_NAME}
      - TEAM_NAME=${TEAM_NAME}
      - EMAIL_HOST=${EMAIL_HOST} 
      - EMAIL_PORT=${EMAIL_PORT} 
      - EMAIL_SECURE=${EMAIL_SECURE} 
      - FROM_EMAIL=${FROM_EMAIL} 
      - EMAIL_PASS=${EMAIL_PASS} 
    ports:
      - ${PORT}:${PORT}
    extra_hosts:
      - "host.docker.internal:host-gateway"
  redis:
    container_name: otpforge-redis
    restart: always
    ports:
      - ${REDIS_EXPOSE_PORT}:6379