version: "3.8"

services:
  api:
    container_name: otpforge-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
  redis:
    container_name: otpforge-redis
    restart: always
    ports:
      - ${REDIS_EXPOSE_PORT}:6379