version: "3.8"

services:
  api:
    container_name: otpforge-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - PORT=${PORT}
      - REDIS_HOST=${REDIS_HOST}
      - OTP_LENGTH=${OTP_LENGTH}
      - INCLUDE_ALPHABETS=${INCLUDE_ALPHABETS}
      - INCLUDE_NUMBERS=${INCLUDE_NUMBERS}
      - OTP_VALIDITY=${OTP_VALIDITY}
    ports:
      - ${PORT}:${PORT}
    extra_hosts:
      - "host.docker.internal:host-gateway"
  redis:
    container_name: otpforge-redis
    restart: always
    ports:
      - ${REDIS_EXPOSE_PORT}:6379