version: "3.8"

services:
  api:
    networks:
      - otpforge-network
    build:
      target: development
    volumes:
      - ./:/usr/src/app
    environment:
      - NODE_ENV=development
    command: npm run dev
  redis:
    image: redis/redis-stack:7.2.0-v8
    networks:
      - otpforge-network
    volumes:
      - ./DATA/REDIS_DATA:/data
    ports:
      - ${REDIS_INSIGHT_EXPOSE_PORT}:8001

networks:
  otpforge-network:
    name: otpforge-network
    driver: bridge
